PRIMERO EN HIZE UN ENLACE DE LOS 3 ARCHIVOS PARA CREAR UNO SOLO Y TENER LA IFORMACION DE LOS 3 AÑOS

In [27]:
import pandas as pd
import glob

# la variable Patrón para encontrar los archivos CSV de ATUS
patron_archivos = '..\\data\\atus_anual_*.csv' #buscara en la ruta de data los arcchivos atus_anual.csv

# Obtener la lista de archivos que coinciden con el patrón
archivos = glob.glob(patron_archivos)

# Imprimir los archivos encontrados
print("Archivos encontrados:")
for archivo in archivos:
    print(archivo)

# Cargar todos los archivos en un solo DataFrame
df_final = pd.concat((pd.read_csv(f) for f in archivos), ignore_index=True)

# Mostrar información sobre el DataFrame resultante
print("\nInformación del DataFrame final:")
print(f"Número de filas: {len(df_final)}")
print(f"Número de columnas: {len(df_final.columns)}")
print("\nPrimeras filas del DataFrame:")
print(df_final.head())

# Opcionalmente, guardar el DataFrame combinado en un nuevo archivo CSV
# df_final.to_csv('atus_combinado.csv', index=False)

Archivos encontrados:
..\data\atus_anual_2021.csv
..\data\atus_anual_2022.csv
..\data\atus_anual_2023.csv

Información del DataFrame final:
Número de filas: 1145653
Número de columnas: 45

Primeras filas del DataFrame:
  COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO   ID_DIA  \
0         1           1          2021     1    0        0          1  Viernes
1         1           1          2021     1    0        0          1  Viernes
2         1           1          2021     1    0        0          1  Viernes
3         1           1          2021     1    0        0          1  Viernes
4         1           1          2021     1    0       50          1  Viernes

                   DIASEMANA                      URBANA  ... PEATMUERTO  \
0  Accidente en intersección  Sin accidente en esta zona  ...          0
1  Accidente en intersección  Sin accidente en esta zona  ...          0
2  Accidente en intersección  Sin accidente en esta zona  ...          0
3  Accidente en intersección  Sin accidente en esta zona  ...          0
4  Accidente en intersección  Sin accidente en esta zona  ...          1

  PEATHERIDO  CICLMUERTO  CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  \
0          0           0           0           0           0         0
1          0           0           0           0           0         0
2          0           0           0           0           0         0
3          0           0           0           0           0         0
4          0           0           0           0           0         0

     NEHERIDO             CLASACC  ESTATUS
0  Sólo daños  Cifras Definitivas      NaN
1  Sólo daños  Cifras Definitivas      NaN
2       Fatal  Cifras Definitivas      NaN
3    No fatal  Cifras Definitivas      NaN
4    No fatal  Cifras Definitivas      NaN

[5 rows x 45 columns]

Cargue en un Dataframe los datos de los accidentes de los últimos 3 años

In [2]:
df = pd.read_csv('..\\data\\atus_combinado.csv')
print(df)

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\3681126273.py:2: DtypeWarning: Columns (0,7,11,24,29,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('..\\data\\atus_combinado.csv')

         COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  \
0                1           1          2021     1    0        0          1
1                1           1          2021     1    0        0          1
2                1           1          2021     1    0        0          1
3                1           1          2021     1    0        0          1
4                1           1          2021     1    0       50          1
...            ...         ...           ...   ...  ...      ...        ...
1145648  Municipal          32            56  2023   12       14         45
1145649  Municipal          32            56  2023   12       21         40
1145650  Municipal          32            56  2023   12       14         30
1145651  Municipal          32            56  2023   12        0          0
1145652  Municipal          32            56  2023   12       18          0

          ID_DIA                  DIASEMANA                        URBANA  \
0        Viernes  Accidente en intersección    Sin accidente en esta zona
1        Viernes  Accidente en intersección    Sin accidente en esta zona
2        Viernes  Accidente en intersección    Sin accidente en esta zona
3        Viernes  Accidente en intersección    Sin accidente en esta zona
4        Viernes  Accidente en intersección    Sin accidente en esta zona
...          ...                        ...                           ...
1145648       27                  Miercoles  Accidente en no intersección
1145649       27                  Miercoles  Accidente en no intersección
1145650       29                    Viernes  Accidente en no intersección
1145651       30                     Sabado  Accidente en no intersección
1145652       31                    Domingo  Accidente en no intersección

         ... PEATMUERTO PEATHERIDO  CICLMUERTO  CICLHERIDO  OTROMUERTO  \
0        ...          0          0           0           0           0
1        ...          0          0           0           0           0
2        ...          0          0           0           0           0
3        ...          0          0           0           0           0
4        ...          1          0           0           0           0
...      ...        ...        ...         ...         ...         ...
1145648  ...          0          0           0           0           0
1145649  ...          0          0           0           0           0
1145650  ...          0          0           0           0           0
1145651  ...          0          0           0           0           0
1145652  ...          0          0           0           0           0

         OTROHERIDO  NEMUERTO    NEHERIDO             CLASACC  \
0                 0         0  Sólo daños  Cifras Definitivas
1                 0         0  Sólo daños  Cifras Definitivas
2                 0         0       Fatal  Cifras Definitivas
3                 0         0    No fatal  Cifras Definitivas
4                 0         0    No fatal  Cifras Definitivas
...             ...       ...         ...                 ...
1145648           0         0           0            No fatal
1145649           0         0           0          Sólo daños
1145650           0         0           0            No fatal
1145651           0         0           0          Sólo daños
1145652           0         0           0          Sólo daños

                    ESTATUS
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
...                     ...
1145648  Cifras Definitivas
1145649  Cifras Definitivas
1145650  Cifras Definitivas
1145651  Cifras Definitivas
1145652  Cifras Definitivas

[1145653 rows x 45 columns]

Agregue una columna tipo date formada por los valores de las columnas correspondientes a Año, Mes, Dia, Hora y Minuto.

In [8]:

import numpy as np

# cargamos el DataFrame
df = pd.read_csv('..\\data\\atus_combinado.csv')

# convertimos columnas a numérico, reemplazando valores no válidos con NaN
for col in ['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# una Función para crear fecha con manejo de valores nulos
def crear_fecha(row):
    try:
        return pd.to_datetime(
            f"{int(row['ANIO'])}-{int(row['MES'])}-{int(row['ID_DIA'])} {int(row['ID_HORA']):02d}:{int(row['ID_MINUTO']):02d}",
            format='%Y-%m-%d %H:%M'
        )
    except:
        return pd.NaT

# creamos la columna de fecha
df['FECHA'] = df.apply(crear_fecha, axis=1)

# mostramos las primeras filas del DataFrame
print("\nPrimeras filas del DataFrame con la nueva columna FECHA:")
print(df[['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO', 'FECHA']].head(10))

# Información sobre la nueva columna FECHA
print("\nInformación sobre la nueva columna FECHA:")
print(df['FECHA'].describe())

# Verificar si hay  fechas nulas
fechas_nulas = df[df['FECHA'].isnull()]
print(f"\nNúmero de fechas nulas: {len(fechas_nulas)}")

if not fechas_nulas.empty:
    print("\nEjemplos de filas con fechas nulas:")
    print(fechas_nulas[['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO']].head())

# Estadísticas de valores nulos en las columnas originales
print("\nEstadísticas de valores nulos en las columnas originales:")
for col in ['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO']:
    print(f"{col}: {df[col].isnull().sum()} valores nulos")

# Opcionalmente, guardar el DataFrame actualizado
#df.to_csv('..\\data\\atus_combinado_con_fecha.csv', index=False)

print("\nLa columna FECHA ha sido agregada al DataFrame original.")

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\691917801.py:4: DtypeWarning: Columns (0,7,11,24,29,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('..\\data\\atus_combinado.csv')

Primeras filas del DataFrame con la nueva columna FECHA:
   ANIO  MES  ID_DIA  ID_HORA  ID_MINUTO FECHA
0     1    0     NaN        0          1   NaT
1     1    0     NaN        0          1   NaT
2     1    0     NaN        0          1   NaT
3     1    0     NaN        0          1   NaT
4     1    0     NaN       50          1   NaT
5     1    1     NaN       24          1   NaT
6     1    2     NaN       30          1   NaT
7     1    4     NaN       20          1   NaT
8     1    7     NaN       10          1   NaT
9     1    8     NaN       25          1   NaT

Información sobre la nueva columna FECHA:
count                           789323
mean     2023-01-03 05:43:46.860740608
min                2022-01-01 00:00:00
25%                2022-07-04 19:01:30
50%                2023-01-02 18:49:00
75%                2023-07-01 14:40:00
max                2023-12-31 23:59:00
Name: FECHA, dtype: object

Número de fechas nulas: 356330

Ejemplos de filas con fechas nulas:
   ANIO  MES  ID_DIA  ID_HORA  ID_MINUTO
0     1    0     NaN        0          1
1     1    0     NaN        0          1
2     1    0     NaN        0          1
3     1    0     NaN        0          1
4     1    0     NaN       50          1

Estadísticas de valores nulos en las columnas originales:
ANIO: 0 valores nulos
MES: 0 valores nulos
ID_DIA: 356315 valores nulos
ID_HORA: 0 valores nulos
ID_MINUTO: 0 valores nulos

La columna FECHA ha sido agregada al DataFrame original.

In [12]:
pd.read_csv('..\\data\\atus_combinado_con_fecha.csv')

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\3281755773.py:1: DtypeWarning: Columns (0,11,24,29,42,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('..\\data\\atus_combinado_con_fecha.csv')

,COBERTURA,ID_ENTIDAD,ID_MUNICIPIO,ANIO,MES,ID_HORA,ID_MINUTO,ID_DIA,DIASEMANA,URBANA,...,PEATHERIDO,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,CLASACC,ESTATUS,FECHA
0,1,1,2021,1,0,0,1,NaN,Accidente en intersección,Sin accidente en esta zona,...,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,NaN,NaN
1,1,1,2021,1,0,0,1,NaN,Accidente en intersección,Sin accidente en esta zona,...,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,NaN,NaN
2,1,1,2021,1,0,0,1,NaN,Accidente en intersección,Sin accidente en esta zona,...,0,0,0,0,0,0,Fatal,Cifras Definitivas,NaN,NaN
3,1,1,2021,1,0,0,1,NaN,Accidente en intersección,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,NaN,NaN
4,1,1,2021,1,0,50,1,NaN,Accidente en intersección,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145648,Municipal,32,56,2023,12,14,45,27.0,Miercoles,Accidente en no intersección,...,0,0,0,0,0,0,0,No fatal,Cifras Definitivas,2023-12-27 14:45:00
1145649,Municipal,32,56,2023,12,21,40,27.0,Miercoles,Accidente en no intersección,...,0,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,2023-12-27 21:40:00
1145650,Municipal,32,56,2023,12,14,30,29.0,Viernes,Accidente en no intersección,...,0,0,0,0,0,0,0,No fatal,Cifras Definitivas,2023-12-29 14:30:00
1145651,Municipal,32,56,2023,12,0,0,30.0,Sabado,Accidente en no intersección,...,0,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,2023-12-30 00:00:00
1145652,Municipal,32,56,2023,12,18,0,31.0,Domingo,Accidente en no intersección,...,0,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,2023-12-31 18:00:00

Agregue una columna para Área cuyos valores serán Urbana o Suburbana dependiendo del área donde ocurrió el accidente.

In [15]:



# Cargar el DataFrame
df = pd.read_csv('..\\data\\atus_combinado.csv')

# Convertir columnas a numérico, reemplazando valores no válidos con NaN
for col in ['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO', 'URBANA', 'SUBURBANA']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Función para crear fecha con manejo de valores nulos
def crear_fecha(row):
    try:
        return pd.to_datetime(
            f"{int(row['ANIO'])}-{int(row['MES'])}-{int(row['ID_DIA'])} {int(row['ID_HORA']):02d}:{int(row['ID_MINUTO']):02d}",
            format='%Y-%m-%d %H:%M'
        )
    except:
        return pd.NaT

# Crear la columna de fecha
df['FECHA'] = df.apply(crear_fecha, axis=1)

# Función para determinar el área
def determinar_area(row):
    if row['URBANA'] == 1:
        return 'Urbana'
    elif row['SUBURBANA'] == 1:
        return 'Suburbana'
    else:
        return 'No especificada'

# Crear la columna de Área
df['AREA'] = df.apply(determinar_area, axis=1)

# Mostrar las primeras filas del DataFrame
print("\nPrimeras filas del DataFrame con las nuevas columnas FECHA y AREA:")
print(df[['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO', 'FECHA', 'URBANA', 'SUBURBANA', 'AREA']].head(10))

# Información sobre la nueva columna FECHA
print("\nInformación sobre la nueva columna FECHA:")
print(df['FECHA'].describe())

# Información sobre la nueva columna AREA
print("\nDistribución de valores en la columna AREA:")
print(df['AREA'].value_counts(dropna=False))

# Verificar fechas nulas
fechas_nulas = df[df['FECHA'].isnull()]
print(f"\nNúmero de fechas nulas: {len(fechas_nulas)}")

if not fechas_nulas.empty:
    print("\nEjemplos de filas con fechas nulas:")
    print(fechas_nulas[['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO']].head())

# Estadísticas de valores nulos en las columnas originales
print("\nEstadísticas de valores nulos en las columnas originales:")
for col in ['ANIO', 'MES', 'ID_DIA', 'ID_HORA', 'ID_MINUTO', 'URBANA', 'SUBURBANA']:
    print(f"{col}: {df[col].isnull().sum()} valores nulos")

# Opcionalmente, guardar el DataFrame actualizado
#df.to_csv('..\\data\\atus_combinado_con_fecha_y_area.csv', index=False)

print("\nLas columnas FECHA y AREA han sido agregadas al DataFrame original.")

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\3694188845.py:4: DtypeWarning: Columns (0,7,11,24,29,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('..\\data\\atus_combinado.csv')

Primeras filas del DataFrame con las nuevas columnas FECHA y AREA:
   ANIO  MES  ID_DIA  ID_HORA  ID_MINUTO FECHA  URBANA  SUBURBANA  \
0     1    0     NaN        0          1   NaT     NaN        NaN
1     1    0     NaN        0          1   NaT     NaN        NaN
2     1    0     NaN        0          1   NaT     NaN        NaN
3     1    0     NaN        0          1   NaT     NaN        NaN
4     1    0     NaN       50          1   NaT     NaN        NaN
5     1    1     NaN       24          1   NaT     NaN        NaN
6     1    2     NaN       30          1   NaT     NaN        NaN
7     1    4     NaN       20          1   NaT     NaN        NaN
8     1    7     NaN       10          1   NaT     NaN        NaN
9     1    8     NaN       25          1   NaT     NaN        NaN

              AREA
0  No especificada
1  No especificada
2  No especificada
3  No especificada
4  No especificada
5  No especificada
6  No especificada
7  No especificada
8  No especificada
9  No especificada

Información sobre la nueva columna FECHA:
count                           789323
mean     2023-01-03 05:43:46.860740608
min                2022-01-01 00:00:00
25%                2022-07-04 19:01:30
50%                2023-01-02 18:49:00
75%                2023-07-01 14:40:00
max                2023-12-31 23:59:00
Name: FECHA, dtype: object

Distribución de valores en la columna AREA:
AREA
No especificada    1145653
Name: count, dtype: int64

Número de fechas nulas: 356330

Ejemplos de filas con fechas nulas:
   ANIO  MES  ID_DIA  ID_HORA  ID_MINUTO
0     1    0     NaN        0          1
1     1    0     NaN        0          1
2     1    0     NaN        0          1
3     1    0     NaN        0          1
4     1    0     NaN       50          1

Estadísticas de valores nulos en las columnas originales:
ANIO: 0 valores nulos
MES: 0 valores nulos
ID_DIA: 356315 valores nulos
ID_HORA: 0 valores nulos
ID_MINUTO: 0 valores nulos
URBANA: 1145653 valores nulos
SUBURBANA: 1145653 valores nulos

Las columnas FECHA y AREA han sido agregadas al DataFrame original.

Agregue una columna Zona cuyos valores serán la zona donde ocurrió el accidente

Elimine las columnas URBANA y SUBURBANA

In [17]:


# Cargar el DataFrame
df = pd.read_csv('..\\data\\atus_combinado_con_fecha_y_area.csv')

# Eliminar las columnas 'URBANA' y 'SUBURBANA'
df = df.drop(['URBANA', 'SUBURBANA'], axis=1)

# Verificar que las columnas han sido eliminadas
print("\nColumnas en el DataFrame después de la eliminación:")
print(df.columns.tolist())

# Mostrar las primeras filas del DataFrame actualizado
print("\nPrimeras filas del DataFrame sin las columnas URBANA y SUBURBANA:")
print(df.head())

# Opcionalmente, guardar el DataFrame actualizado
#df.to_csv('..\\data\\atus_combinado_final.csv', index=False)

print("\nLas columnas URBANA y SUBURBANA han sido eliminadas del DataFrame.")

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\493022489.py:2: DtypeWarning: Columns (0,11,24,29,42,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('..\\data\\atus_combinado_con_fecha_y_area.csv')

Columnas en el DataFrame después de la eliminación:
['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA', 'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'TIPACCID', 'AUTOMOVIL', 'CAMPASAJ', 'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA', 'CAMIONETA', 'CAMION', 'TRACTOR', 'FERROCARRI', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC', 'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO', 'CINTURON', 'ID_EDAD', 'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO', 'PASAHERIDO', 'PEATMUERTO', 'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO', 'OTROMUERTO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO', 'CLASACC', 'ESTATUS', 'FECHA', 'AREA']

Primeras filas del DataFrame sin las columnas URBANA y SUBURBANA:
  COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  ID_DIA  \
0         1           1          2021     1    0        0          1     NaN
1         1           1          2021     1    0        0          1     NaN
2         1           1          2021     1    0        0          1     NaN
3         1           1          2021     1    0        0          1     NaN
4         1           1          2021     1    0       50          1     NaN

                   DIASEMANA TIPACCID  ...  CICLMUERTO  CICLHERIDO  \
0  Accidente en intersección        3  ...           0           0
1  Accidente en intersección        1  ...           0           0
2  Accidente en intersección        1  ...           0           0
3  Accidente en intersección        1  ...           0           0
4  Accidente en intersección        1  ...           0           0

   OTROMUERTO  OTROHERIDO  NEMUERTO    NEHERIDO             CLASACC  ESTATUS  \
0           0           0         0  Sólo daños  Cifras Definitivas      NaN
1           0           0         0  Sólo daños  Cifras Definitivas      NaN
2           0           0         0       Fatal  Cifras Definitivas      NaN
3           0           0         0    No fatal  Cifras Definitivas      NaN
4           0           0         0    No fatal  Cifras Definitivas      NaN

   FECHA             AREA
0    NaN  No especificada
1    NaN  No especificada
2    NaN  No especificada
3    NaN  No especificada
4    NaN  No especificada

[5 rows x 45 columns]

Las columnas URBANA y SUBURBANA han sido eliminadas del DataFrame.

In [18]:
print(df.columns)

Index(['COBERTURA', 'ID_ENTIDAD', 'ID_MUNICIPIO', 'ANIO', 'MES', 'ID_HORA',
       'ID_MINUTO', 'ID_DIA', 'DIASEMANA', 'TIPACCID', 'AUTOMOVIL', 'CAMPASAJ',
       'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA', 'CAMIONETA', 'CAMION',
       'TRACTOR', 'FERROCARRI', 'MOTOCICLET', 'BICICLETA', 'OTROVEHIC',
       'CAUSAACCI', 'CAPAROD', 'SEXO', 'ALIENTO', 'CINTURON', 'ID_EDAD',
       'CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO', 'PASAHERIDO', 'PEATMUERTO',
       'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO', 'OTROMUERTO', 'OTROHERIDO',
       'NEMUERTO', 'NEHERIDO', 'CLASACC', 'ESTATUS', 'FECHA', 'AREA'],
      dtype='object')

Determine cual municipio de cada estado tuvo más meses sin accidentes

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar el DataFrame
df = pd.read_csv('..\\data\\atus_combinado_final.csv')

# 1. Municipio con más meses sin accidentes por estado
def meses_sin_accidentes(grupo):
    todos_meses = set(range(1, 13))
    meses_con_accidentes = set(grupo['MES'].unique())
    return len(todos_meses - meses_con_accidentes)

municipios_sin_accidentes = df.groupby(['ID_ENTIDAD', 'ID_MUNICIPIO']).apply(meses_sin_accidentes).reset_index()
municipios_sin_accidentes.columns = ['ID_ENTIDAD', 'ID_MUNICIPIO', 'MESES_SIN_ACCIDENTES']
municipios_max_sin_accidentes = municipios_sin_accidentes.loc[municipios_sin_accidentes.groupby('ID_ENTIDAD')['MESES_SIN_ACCIDENTES'].idxmax()]

print("1. Municipios con más meses sin accidentes por estado:")
print(municipios_max_sin_accidentes)

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\397457624.py:5: DtypeWarning: Columns (0,9,22,27,40,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('..\\data\\atus_combinado_final.csv')

1. Municipios con más meses sin accidentes por estado:
      ID_ENTIDAD  ID_MUNICIPIO  MESES_SIN_ACCIDENTES
0              1             1                     0
12             2             1                     0
18             3             1                     0
24             4             1                     0
38             5             1                     0
...          ...           ...                   ...
2917         566          2021                    12
2918         567          2021                    12
2919         568          2021                    12
2920         569          2021                    12
2921         570          2021                     4

[570 rows x 3 columns]

C:\Users\salaz\AppData\Local\Temp\ipykernel_19076\397457624.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  municipios_sin_accidentes = df.groupby(['ID_ENTIDAD', 'ID_MUNICIPIO']).apply(meses_sin_accidentes).reset_index()

Resuma los accidentes del último año por tipo y que porcentaje representan

In [20]:
#  Resumen de accidentes del último año por tipo
ultimo_anio = df['ANIO'].max()
accidentes_ultimo_anio = df[df['ANIO'] == ultimo_anio]['TIPACCID'].value_counts()
porcentaje_accidentes = (accidentes_ultimo_anio / accidentes_ultimo_anio.sum() * 100).round(2)

print("\n2. Resumen de accidentes del último año por tipo:")
print(pd.DataFrame({'Cantidad': accidentes_ultimo_anio, 'Porcentaje': porcentaje_accidentes}))

2. Resumen de accidentes del último año por tipo:
                                       Cantidad  Porcentaje
TIPACCID
Colisión con vehículo automotor          232509       58.62
Colisión con motocicleta                  57421       14.48
Colisión con objeto fijo                  44233       11.15
Certificado cero                          15580        3.93
Colisión con peatón (atropellamiento)     11853        2.99
Volcadura                                 11449        2.89
Salida del camino                         10232        2.58
Otro                                       5805        1.46
Colisión con ciclista                      3928        0.99
Caída de pasajero                          1947        0.49
Colisión con animal                        1026        0.26
Incendio                                    381        0.10
Colisión con ferrocarril                    264        0.07

Obtenga la cantidad de muertos y lesionados de los últimos 3 años

In [26]:
# Función para convertir columnas a numérico, manejando errores
def to_numeric_safe(df, column):
    df[column] = pd.to_numeric(df[column], errors='coerce')
    return df

# Lista de columnas a convertir
columnas_numericas = ['CONDMUERTO', 'CONDHERIDO', 'PASAMUERTO', 'PASAHERIDO',
                      'PEATMUERTO', 'PEATHERIDO', 'CICLMUERTO', 'CICLHERIDO',
                      'OTROMUERTO', 'OTROHERIDO', 'NEMUERTO', 'NEHERIDO']

# Aplicar la conversión a todas las columnas necesarias
for col in columnas_numericas:
    df = to_numeric_safe(df, col)

#  Cantidad de muertos y lesionados de los últimos 3 años
ultimos_3_anios = df['ANIO'].unique()[-3:]
muertos_lesionados = df[df['ANIO'].isin(ultimos_3_anios)].groupby('ANIO').agg({
    col: 'sum' for col in columnas_numericas
})

muertos_lesionados['Total_Muertos'] = muertos_lesionados[[col for col in muertos_lesionados.columns if 'MUERTO' in col]].sum(axis=1)
muertos_lesionados['Total_Heridos'] = muertos_lesionados[[col for col in muertos_lesionados.columns if 'HERIDO' in col]].sum(axis=1)

print("\n3. Cantidad de muertos y lesionados de los últimos 3 años:")
print(muertos_lesionados[['Total_Muertos', 'Total_Heridos']])

# Verificar si hay valores nulos después de la conversión
nulos_despues_conversion = df[columnas_numericas].isnull().sum()
print("\nValores nulos después de la conversión:")
print(nulos_despues_conversion)

# Si hay valores nulos, mostrar algunas filas de ejemplo
if nulos_despues_conversion.sum() > 0:
    print("\nEjemplos de filas con valores no numéricos:")
    filas_problematicas = df[df[columnas_numericas].isnull().any(axis=1)]
    print(filas_problematicas[['ANIO'] + columnas_numericas].head())

3. Cantidad de muertos y lesionados de los últimos 3 años:
      Total_Muertos  Total_Heridos
ANIO
12             7963          187.0
2022           5181        91501.0
2023           4803        90500.0

Valores nulos después de la conversión:
CONDMUERTO         0
CONDHERIDO         0
PASAMUERTO         0
PASAHERIDO         0
PEATMUERTO         0
PEATHERIDO         0
CICLMUERTO         0
CICLHERIDO         0
OTROMUERTO         0
OTROHERIDO         0
NEMUERTO           0
NEHERIDO      356315
dtype: int64

Ejemplos de filas con valores no numéricos:
   ANIO  CONDMUERTO  CONDHERIDO  PASAMUERTO  PASAHERIDO  PEATMUERTO  \
0     1           0           0           0           0           0
1     1           0           0           0           0           0
2     1           0           0           0           1           0
3     1           1           0           0           0           0
4     1           0           0           0           0           1

   PEATHERIDO  CICLMUERTO  CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  \
0           0           0           0           0           0         0
1           0           0           0           0           0         0
2           0           0           0           0           0         0
3           0           0           0           0           0         0
4           0           0           0           0           0         0

   NEHERIDO
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

¿Cómo se compara el número de accidentes de cada año contra el anterior? ¿En qué porcentaje varió?

In [23]:
#4. Comparación del número de accidentes por año
accidentes_por_anio = df.groupby('ANIO').size()
variacion_porcentual = accidentes_por_anio.pct_change() * 100

print("\n4. Comparación del número de accidentes por año y variación porcentual:")
print(pd.DataFrame({'Número de Accidentes': accidentes_por_anio, 'Variación Porcentual': variacion_porcentual}))

4. Comparación del número de accidentes por año y variación porcentual:
      Número de Accidentes  Variación Porcentual
ANIO
1                    26772                   NaN
2                    25730             -3.892126
3                    30012             16.642052
4                    28759             -4.174997
5                    31224              8.571230
6                    29529             -5.428517
7                    29725              0.663754
8                    28584             -3.838520
9                    28664              0.279877
10                   32212             12.377896
11                   31124             -3.377623
12                   33980              9.176198
2022                392710           1055.709241
2023                396628              0.997683

Seleccione una o dos características y haga una gráfica de cada una de las siguientes:

Histograma

In [24]:
#  Histograma de edades
plt.figure(figsize=(10, 6))
sns.histplot(df['ID_EDAD'], bins=20, kde=True)
plt.title('Histograma de Edades de los Involucrados en Accidentes')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.savefig('histograma_edades.png')
plt.close()

BARRAS

In [25]:
#  Gráfico de barras de tipos de accidentes
plt.figure(figsize=(12, 6))
df['TIPACCID'].value_counts().plot(kind='bar')
plt.title('Frecuencia de Tipos de Accidentes')
plt.xlabel('Tipo de Accidente')
plt.ylabel('Frecuencia')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('barras_tipos_accidentes.png')
plt.close()